// gen-tts.js
// Generates OpenAI gpt-4o-mini-tts audio for every unique Spanish sentence and
// segment in translation-data.js. Idempotent: re-running only generates files
// that don't yet exist on disk.
//
// Setup:
//   npm install
//   export OPENAI_API_KEY=sk-...
//   node gen-tts.js

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const OpenAI = require("openai");

const MODEL = "gpt-4o-mini-tts";
const VOICE = "onyx";
const SPEED = 1.25;
const INSTRUCTIONS =
  "Use bright and engaging intonation, like a passionate teacher getting kids excited by better understanding unique implications.";
const FORMAT = "mp3";
const CONCURRENCY = 6;
const SAVE_MANIFEST_EVERY = 50;

const OUT_DIR = "audio";
const MANIFEST_JS = "audio-manifest.js";
const MANIFEST_JSON = path.join(OUT_DIR, "manifest.json");

fs.mkdirSync(OUT_DIR, { recursive: true });

const src = fs.readFileSync("translation-data.js", "utf8");
const translationData = eval(src + "\n; translationData;");

const strings = new Set();
for (const c of translationData) {
  for (const s of c.sentences || []) {
    if (s.spanish) strings.add(s.spanish.trim());
    if (s.segments && Array.isArray(s.segments.spanish)) {
      for (const seg of s.segments.spanish) strings.add(seg.trim());
    }
  }
}
const ALL = [...strings].filter(Boolean);
console.log(`Found ${ALL.length} unique Spanish strings.`);

function hashName(text) {
  return (
    crypto
      .createHash("sha256")
      .update(text.normalize("NFC"))
      .digest("hex")
      .slice(0, 16) +
    "." +
    FORMAT
  );
}

let manifest = {};
if (fs.existsSync(MANIFEST_JSON)) {
  try {
    manifest = JSON.parse(fs.readFileSync(MANIFEST_JSON, "utf8"));
  } catch {
    manifest = {};
  }
}

const openai = new OpenAI();

async function generate(text) {
  const filename = hashName(text);
  const filepath = path.join(OUT_DIR, filename);
  manifest[text] = filename;
  if (fs.existsSync(filepath)) return { skipped: true };

  const response = await openai.audio.speech.create({
    model: MODEL,
    voice: VOICE,
    input: text,
    speed: SPEED,
    instructions: INSTRUCTIONS,
    response_format: FORMAT,
  });
  const buffer = Buffer.from(await response.arrayBuffer());
  fs.writeFileSync(filepath, buffer);
  return { skipped: false };
}

function writeManifest() {
  fs.writeFileSync(MANIFEST_JSON, JSON.stringify(manifest, null, 2));
  const js =
    "// Auto-generated by gen-tts.js. Do not edit by hand.\n" +
    "window.AUDIO_MANIFEST = " +
    JSON.stringify(manifest) +
    ";\n";
  fs.writeFileSync(MANIFEST_JS, js);
}

let cursor = 0;
let done = 0;
let made = 0;
let skipped = 0;
const failures = [];

async function worker() {
  while (cursor < ALL.length) {
    const text = ALL[cursor++];
    try {
      const r = await generate(text);
      if (r.skipped) skipped++;
      else made++;
      done++;
      if (done % SAVE_MANIFEST_EVERY === 0) writeManifest();
      if (done % 25 === 0 || done === ALL.length) {
        const preview = text.length > 60 ? text.slice(0, 57) + "..." : text;
        console.log(
          `  ${done}/${ALL.length}  made=${made} skip=${skipped}  ${preview}`,
        );
      }
    } catch (e) {
      failures.push({ text, error: e.message });
      console.error(`FAIL: ${text.slice(0, 60)} — ${e.message}`);
    }
  }
}

async function main() {
  if (!process.env.OPENAI_API_KEY) {
    console.error("OPENAI_API_KEY env var is not set. Aborting.");
    process.exit(1);
  }
  const start = Date.now();
  await Promise.all(Array.from({ length: CONCURRENCY }, () => worker()));
  writeManifest();
  const secs = ((Date.now() - start) / 1000).toFixed(1);
  console.log("");
  console.log(`Done in ${secs}s. Generated ${made}, skipped ${skipped}.`);
  if (failures.length) {
    console.log(
      `${failures.length} failures — re-run \`node gen-tts.js\` to retry them.`,
    );
  }
  console.log(`Wrote ${MANIFEST_JS} and ${MANIFEST_JSON}.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
