name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create config with API keys
        run: |
          echo "window.SPEECH_CONFIG = {" > public/js/config.production.js
          echo "  apiKey: '${{ secrets.SPEECH_API_KEY }}'," >> public/js/config.production.js
          echo "  region: '${{ secrets.SPEECH_REGION }}'," >> public/js/config.production.js
          echo "  voiceName: 'es-ES-ElviraNeural'," >> public/js/config.production.js
          echo "  fallbackVoiceName: 'es-ES-AlvaroNeural'," >> public/js/config.production.js
          echo "  pitch: 0," >> public/js/config.production.js
          echo "  rate: 1.0," >> public/js/config.production.js
          echo "  useSSML: false," >> public/js/config.production.js
          echo "  useFallbackVoices: true" >> public/js/config.production.js
          echo "};" >> public/js/config.production.js
      
      - name: Update index.html to use production config
        run: |
          sed -i 's|<script src="js/config.js"></script>|<script src="js/config.production.js"></script>|g' public/index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3