name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create config with API keys
        run: |
          echo "window.SPEECH_CONFIG = {" > public/js/config.production.js
          echo "  apiKey: '${{ secrets.SPEECH_API_KEY }}'," >> public/js/config.production.js
          echo "  region: '${{ secrets.SPEECH_REGION }}'," >> public/js/config.production.js
          echo "  voiceName: 'es-ES-ElviraNeural'," >> public/js/config.production.js
          echo "  fallbackVoiceName: 'es-ES-AlvaroNeural'," >> public/js/config.production.js
          echo "  pitch: 0," >> public/js/config.production.js
          echo "  rate: 1.0," >> public/js/config.production.js
          echo "  useSSML: false," >> public/js/config.production.js
          echo "  useFallbackVoices: true" >> public/js/config.production.js
          echo "};" >> public/js/config.production.js
      
      - name: Update index.html to use production config
        run: |
          sed -i 's|<script src="js/config.js"></script>|<script src="js/config.production.js"></script>|g' public/index.html
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public